### PR TITLE
JVM backends using http4s-jdk client

### PR DESCRIPTION
**Pull request by rpiaggio**

### CODE REVIEW

**Comment by cquiroz** [comment]
Do we want to replace sttp? Is this mean for backend calls?

**Comment by rpiaggio** [comment]
> Do we want to replace sttp? Is this mean for backend calls?

We don't actually use sttp in clue, only its model, in order to have the `Uri` type. clue has its own mechanism to abstract away connection mechanisms via implementations of `TransactionalBackend` and `WebSocketBackend`.

Until now, we only had implementations for JS, using JS's `Ajax` and `WebService`.

This PR allows clue to be actually used in JVM via https://jdk-http-client.http4s.org/

**Comment by rpiaggio** [comment]
BTW, this requires Java 11+.

**Comment by cquiroz** [comment]
Would it make sense to just use `sttp` as it is available for both platforms?

**Review by cquiroz — APPROVED** [review]
LGTM, Still not sure if it maybe better to use `sttp` as a universal http client

**Pull request merged**
