### PR TITLE
Support sending authentication on the websocket channel

### PR DESCRIPTION
**Pull request by cquiroz**
Signed-off-by: Carlos Quiroz <carlos.m.quiroz@gmail.com>

### CODE REVIEW

**Comment by rpiaggio** [comment]
Thank you for this. My only comment is that I'd like to keep the API close to the protocol, which in this case allows for a generic `payload` object to be included in the `connection_init` message, while this PR is specific to bearer autorization.

Could we keep the API generic while building the specific `Authorization` field at the call site. I guess we could pass anything as the `payload` as long as there's an `Encoder` for it.

**Comment by cquiroz** [comment]
Yeah I wondered about that, I was mostly trying to get this to run against the backend.
I guess the payload is just a Strinf right? We wouldn't assume it is json for example?

**Comment by rpiaggio** [comment]
> Yeah I wondered about that, I was mostly trying to get this to run against the backend.
> I guess the payload is just a Strinf right? We wouldn't assume it is json for example?

The payload seems to be an object: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_init

**Comment by rpiaggio** [comment]
I reworked things a bit:

* The concepts of a `GraphQLStreamingClient` and a `PersistentClient` are now separate. The former allows clients to `subscribe` (besides executing queries and mutations), and the latter implies a persistent connection to the server.
* There's also a `GraphQLPersistentStreamingClient` which just combines both. `ApolloStreamingClient` extends it.
* A `PersistentClient` now requires an explicit call to `connect(payload: JsonObject)`. In particular, `ApolloStreamingClient` sends the `payload` in its `connection_init` message.

There's also an unrelated change which is the new `GraphQLSubscription` type, which is now independent of the client type. This simplifies the client code.

There were also some adjustments to the types of some messages payloads, changing them from `Json` to `JsonObject` whenever the spec mentions they are an `object`.

All of these are BREAKING CHANGES.

**Review by cquiroz — COMMENTED** [review]
Thanks @rpiaggio for the improvements, it looks great

**Comment by rpiaggio** [comment]
Thank you.

I'm adding another commit that also adds a `ReconnectionStrategy` and getting the connection parameters as an effect, which allows us to get the latest token whenever it's necessary.

**Pull request merged**
